### ISSUE TITLE
Falta link de navegacao entre os arquivos

### ISSUE THREAD

**Issue by paulocuambe** [Novout/vue4noobs#19]
Ao seguir os artigos, constatei que preciso sempre voltar a pagina docs/README.md. O que é muito cansativo.

Acho que seria mais eficiente se houvesse algum link entre os artigos que aponte para o próximo e se possível o anterior também.

Estou disponível a ajudar na resolução desse pequeno problema, caso seja possível vou criar um PR e mandar para la as modificações. Por não querer fazer trabalho duplicado, porque provavelmente você ou outra pessoa pode estar a trabalhar nisso nesse momento, abri essa issue.

**Comment by Novout** [comment]
Obrigado pelo feedback. No momento estamos portando os 4noobs para um site, que é o motivo por não termos colocado botôes de voltar no markdown.Ainda não temos previsão de quando o site irá ao ar, então se quiser mandar um PR fique á vontade :)

**Comment by paulocuambe** [comment]
@Novout certo. Valeu pela rapida resposta. Vou deixar essa issue aberta por enquanto, assim que mandar o PR fecho ela.

**Comment by paulocuambe** [comment]
Vou fechar a issue.

Acho que não faz sentido ter esses links se os artigos vão estar num site. Provavelmente terão um mecanismo automático pra isso.

Mais uma vez obrigado.
