### ISSUE TITLE
Colocar um exemplo de como importar o vue router

### ISSUE THREAD

**Issue by vduggen** [Novout/vue4noobs#24]
Na parte de adicionando o vue router no projeto, tem que importar no **main.js** o vue-router, mas não deram um exemplo de como pode fazer, se tiverem como colocar fica melhor pra orientar quem ainda não conhece como faz o processo

![image](https://user-images.githubusercontent.com/53385727/100468143-95c59d00-30b2-11eb-9eb1-460c500b1fef.png)

**Comment by Novout** [comment]
Feito! Obrigado pelo feedback! :)
