### ISSUE TITLE
Colocar uma seção de boas práticas com o framework

### ISSUE THREAD

**Issue by vduggen** [Novout/vue4noobs#25]
Acho interessante pra quem ta começando, logo após ter passado pelo tutorial inteiro, saber como ele pode fazer as coisas de uma forma certa e seguir algum padrão

**Comment by Novout** [comment]
O Vue4noobs já segue os padrões recomendados para se utilizar o vue, como nomeações e utilização de recursos, não pretendemos colocar padronizações de pasta ou componentização pois isso depende do projeto.
