### ISSUE TITLE
Revisão Módulo 1 - O que é Vue

### ISSUE THREAD

**Issue by netojocelino** [Novout/vue4noobs#27]
Ao ler a página [O que é Vue](https://novout.github.io/vue4noobs/tutorial/1-Iniciando%20com%20Vue/1-O%20que%20e%20Vue.html) percebi duas minusculas modificações que podem ser corrigidos (posso até mandar o PR, por ser coisa pouca), onde o link para o discord está quebrado (como se fosse um link para o próprio repositório), onde adicionar um _https://_ já resolve e o seguinte é no texto que no trecho 

> Para manipular, o Vue utiliza um sistemas de componentes com a extensão .vue. 

Onde acredito que poderia ser rescrito como

> Para manipular, o Vue utiliza um sistema de componentes com a extensão .vue.
 
 
 Caso necessário, mesmo sendo pequenos os ajustes posso alterar.

**Comment by Novout** [comment]
Corrigido!
